### ISSUE TITLE
OneNoteConnection error

### ISSUE THREAD

**Issue by ikarmus2001** [theohbrothers/ConvertOneNote2MarkDown#121]
## Bug

Unable to find type [Microsoft.Office.InterOp.OneNote.HierarchyScope]

Output:
```powershell
Convert-OneNote2MarkDown : Unable to find type [Microsoft.Office.InterOp.OneNote.HierarchyScope].
At D:\Nie-gry\OnenoteToObsidian\ConvertOneNote2MarkDown\ConvertOneNote2MarkDown-v2.ps1:1423 char:5
+     Convert-OneNote2MarkDown @params
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Convert-OneNote2MarkDown

Convert-OneNote2MarkDown : at Get-OneNoteHierarchy, D:\Nie-gry\OnenoteToObsidian\ConvertOneNote2MarkDown\ConvertOneNote2MarkDown-v2.ps1: line 568
at Convert-OneNote2MarkDown, D:\Nie-gry\OnenoteToObsidian\ConvertOneNote2MarkDown\ConvertOneNote2MarkDown-v2.ps1: line 1362
at <ScriptBlock>, D:\Nie-gry\OnenoteToObsidian\ConvertOneNote2MarkDown\ConvertOneNote2MarkDown-v2.ps1: line 1423
at <ScriptBlock>, <No file>: line 1
At D:\Nie-gry\OnenoteToObsidian\ConvertOneNote2MarkDown\ConvertOneNote2MarkDown-v2.ps1:1423 char:5
+     Convert-OneNote2MarkDown @params
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Convert-OneNote2MarkDown

Cleaning up...
Exiting.
```

## Expectation

Execute properly.

## Discussion

Script starts, writes up configuration (read config example and edited properties)

- Backed up all my Notes from OneNote dir (standard one, appdata/local)
- made up my config
- tried to run script **without Pandoc installed** which obviously resulted errors
- downloaded and installed Pandoc, checked versions of win and onenote + word
- checked Pandoc (cmd pandoc.exe runs properly)
- rebooted pc
- error as above

It may be important - I'm running script from VSC powershell, it shouldn't make any troubles, right?

## Environment

Win10 Home x64  21H2

OneNote 2016 from Office Professional Plus 2019 (somehow)
16.0.10382.20034, version 1808, compilation 10382.20034 quick-installation

Word 2016 from Office Professional Plus 2019
16.0.10382.20034, version 1808, compilation 10382.20034 quick-installation (same as onenote)

Pandoc 2.17.1.1 (.msi installer, hope it installed properly)

**Output of Configuration**

```powershell
Configuration:
dryRun: 1
notesdestpath: D:\Nie-gry\converted_notes
targetNotebook: 
usedocx: 1
keepdocx: 1
docxNamingConvention: 1
prefixFolders: 2
mdFileNameAndFolderNameMaxLength: 128
medialocation: 2
conversion: markdown-simple_tables-multiline_tables-grid_tables+pipe_tables
headerTimestampEnabled: 1
keepspaces: 1
keepescape: 1
newlineCharacter: 2
exportPdf: 1
```

**Output of `$PSVersionTable`**

```powershell
PS > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1320
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1320
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by ikarmus2001** [comment]
I also noticed that script broke my OneNote (random shutdowns and restarts, creating sections on itself). Now I'm reinstalling whole Office, hope it fixes issue.

**Comment by tanjoe** [comment]
Had the same problem. Trying to export the note as docx with OneNote will cause OneNote to crash in the first place, so it seems like a bug caused by OneNote itself. These crashed notes are all clipped with OneNote Web Clipper but their content seems normal to me, and not all clipped notes will crash, so I didn't find a pattern about this.
The Office version I'm using is 16.0.14827.20198

**Comment by leojonathanoh** [comment]
@ikarmus2001 the script does break Onenote. As said in the readme during the conversion process, the UI will be "blocked" or less responsive that normal. It is important to stop the conversion before beginning to use OneNote again.

**Comment by leojonathanoh** [comment]
> Had the same problem. Trying to export the note as docx with OneNote will cause OneNote to crash in the first place, so it seems like a bug caused by OneNote itself. These crashed notes are all clipped with OneNote Web Clipper but their content seems normal to me, and not all clipped notes will crash, so I didn't find a pattern about this.
> The Office version I'm using is 16.0.14827.20198

You are right that if the inbuilt OneNote Export function crashes in the first place, the Page itself is "bugged" so recreating it will solve the issue. I use to have random notes in my notebook that did this, the even led to exporting the notebook to fail. The solution was to delete the notebook and redownload it from Onedrive, then exporting worked. Seems like the redownloading of the notebook recreates the pages from scrach. 

I'd think the cause is migrating between older version of OneNote to newer versions. My notes that had this problem were about 8-10 years old, which was created on a OneNote on Windows 8.1. That old version might have had some bugs that were retained throughout the many years until I finally exported the notebook on Windows 10 a few years later.

**Comment by leojonathanoh** [comment]
Related: #5. 

Very probable cause: https://github.com/theohbrothers/ConvertOneNote2MarkDown/issues/5#issuecomment-888935094
