### ISSUE TITLE
Onenote code formatting doesn't get converted to markdown code blocks

### ISSUE THREAD

**Issue by deepaksood619** [theohbrothers/ConvertOneNote2MarkDown#144]
## Current

State the current behavior in one sentence.

Onenote code formatting doesn't get converted to markdown code blocks

## Expectation

State the feature in one sentence.
The code should be converted to markdown code blocks using ```

Ex - 
```
import sqllite3
```

## Discussion

Describe the feature.

**Comment by leojonathanoh** [comment]
Hey @deepaksood619 , the conversion process first converts the onenote page to a `.docx`, and then the `.docx` is converted to markdown using pandoc. I'd think that the code fences should be preserved in the intermediate `.docx`, but that pandoc escapes the code fences because it sees the content in the `.docx` which is a WYSIWYG editor, hence code fences appear as is in the final markdown (i.e. markdown-escaped), hence the result you see. 

I don't know pandoc well enough to know whether it has an extension that can work around this behavior. Perhaps others might have an idea.

**Comment by leojonathanoh** [comment]
Looking at this again, since Onenote is a WYSIWYG editor, whatever is seen should be preserved entirely. Hence, if one wrote markdown content in Onenote, the final converted `.md` file will markdown-escape the entire original markdown content. At this point I do not know how to make pandoc not markdown-escape the original markdown content in Onenote.

Closing.
