### ISSUE TITLE
Latest stable Powershell support

### ISSUE THREAD

**Issue by fromSmolsoft** [theohbrothers/ConvertOneNote2MarkDown#162]
## Current
Script doesn't work with PowerShell 7.3.5

## Expectation
Script should work with PowerShell 7.3.5+ ( latest stable release at the time). 

## Discussion
It would be good to follow up-to-date version of PowerShell since it seems to be widely used.  
Chocolatey downloads of latest stable release counts 3,453,262 assuming most people update regularly.
Windows updater updates PowerShell to latest version. 

It would be better then install older version just to run single script. 

Thank you for your time and efforts.

**Comment by leojonathanoh** [comment]
I agree that the script should support the latest powershell version. It actually does, but Microsoft has removed support for importing GAC assemblies (i.e. win32 assemblies) since powershell 7.1 and above. See: https://github.com/theohbrothers/ConvertOneNote2MarkDown/blob/master/ConvertOneNote2MarkDown-v2.ps1#L543-L547, which is needed for using OneNote APIs.

Unless they have changed something recently, it's only possible to use Windows Powershell or Powershell Core up to 6.x.x to 7.0.x. 

I will make this clearer in the docs.
