### ISSUE TITLE
CategoryInfo Write-Error

### ISSUE THREAD

**Issue by dschinkel** [theohbrothers/ConvertOneNote2MarkDown#175]
Not sure what to make of this Category error, can you please help me understand why this errored?  What category or thing is it talking about?

<img width="1398" alt="Screenshot 2023-11-19 030342" src="https://github.com/theohbrothers/ConvertOneNote2MarkDown/assets/338798/9a143b89-57fc-48c9-895c-a15b2897f9a4">

**Comment by dschinkel** [comment]
how stupid, I assumed if you hit enter, it'd just use defaults but in fact it was passing no params.  So you have to select something in the prompts

**Comment by leojonathanoh** [comment]
Hey @dschinkel. Thanks for the bug report. The script does fill in default values when pressing `ENTER`, and the configuration printed out at the beginning of the script all looks filled in correctly, so this error is not caused by no params being passed, but the cause for this error is documented the [FAQ](https://github.com/theohbrothers/ConvertOneNote2MarkDown#error-80080005-server-execution-failed-exception-from-hresult-0x80080005co_e_server_exec_failure). 

Regardless, there should be better error messages directing the user to the FAQ to resolve errors.
