### ISSUE TITLE
Feature: Add selectable notebook

### ISSUE THREAD

**Issue by magi44ken** [theohbrothers/ConvertOneNote2MarkDown#18]
Hi, can you add an option to allow user to select which notebook to convert? Alxnbl wrote a PowerShell script with this option that you can check it out. Thanks.

https://github.com/alxnbl/onenote-md-exporter

**Comment by nixsee** [comment]
Sorry, I dont have time for this. If you or someone else wants to submit a pull request for this, that would be great. Otherwise I recommend you just temporarily close the notebooks that you don't want to export.

**Comment by leojonathanoh** [comment]
@magi44ken i have created a fork implementing this. https://github.com/theohbrothers/ConvertOneNote2MarkDown

**Comment by nixsee** [comment]
@leojonathanoh Nice work! You're clearly an actual developer, whereas I just hacked around til it worked. 

Its unlikely that I will be adding to or even maintaining this going forward. Do you plan to continue making enhancements to this? If so, is there a way that I could officially pass the project off to you? Make you the owner of this repo? Just put a link to your repo in my readme? 

I ask because people will still likely end up coming to my repo due to links that are out in the web, and I'd like for them to get the best version available

**Comment by leojonathanoh** [comment]
@nixsee i am currently making enhancements as much as i am going to be planning to be converting a few GB of notebooks (about 10 notebooks or so) over the next few days. Sure, I don't mind being the owner, i'd like a working and generic version for everybody.

**Comment by leojonathanoh** [comment]
@nixsee perhaps you could add a link to your profile in the readme before you transfer the ownership. Transfer it @theohbrothers, i've renamed my current fork :)

**Comment by nixsee** [comment]
Ok great, I'll figure that out shortly. Glad to see that this will get improved and maintained for a while longer. Please pass it on to someone else if you decide to stop working on it!

**Comment by leojonathanoh** [comment]
@nixsee i actually foresee many more people going to be using this as i've come to realize documentation is far better in markdown than any other format. My brother and I should be able to maintain this for some time, since our notebooks we are migrating have a lot of notes and we need a very solid migrator to ensure that our notes are completely and perfectly migrated.

**Comment by nixsee** [comment]
Great. I couldn't transfer because you already have a repo with the same name. I don't know if you want to just delete it and I can try again, or I'll just leave a bunch of notices to make it clear that this is deprecated and to go to your repo?

**Comment by leojonathanoh** [comment]
@nixsee let me check

**Comment by nixsee** [comment]
@leojonathanoh

The error message I received: 

"theohbrothers already has a repository in the SjoerdV/ConvertOneNote2MarkDown network and You don’t have the permission to create public repositories on theohbrothers"

**Comment by leojonathanoh** [comment]
@nixsee  ok i moved my fork to my own namespace, you can try now

**Comment by nixsee** [comment]
still doesnt work - i dont have permission to create a repo on theohbrothers.

I'll just make it clear that this is deprecated and link to yours. Good luck!

Also, check out rab-bit's fork, or the forks of that fork... They made various enhancements and submitted pull requests, but it wasn't well documented so I just rejected it rather than incorporating something I didn't understand. Perhaps there's something of use in there for you.

**Comment by leojonathanoh** [comment]
@nixsee i think i might have to add you to my org with permissions, sec

**Comment by nixsee** [comment]
@leojonathanoh I got an invite, but it looks like you cancelled it. Try again?

**Comment by leojonathanoh** [comment]
@nixsee lemme try again

**Comment by leojonathanoh** [comment]
@nixsee done

**Comment by leojonathanoh** [comment]
@nixsee i've added u as a collab in the case u ever want to take over the repo again :)

**Comment by nixsee** [comment]
cool! I doubt it, but good to know. I've got a lot to focus on, and its ultimately in far better hands now. Enjoy!

I also updated the link in my obsidian forum post, where most people find this. https://forum.obsidian.md/t/new-tool-for-migration-from-onenote-updated-and-improved-version/

If you use obisidian, feel free to make a new thread and I'll link to that as well

**Comment by leojonathanoh** [comment]
@nixsee the readme doesn't seem to mentioned you as the original author of this repository so i'll revise it to be clearer. 

As of yet i haven't tried obisidian but it could very well be an option, so i'll update you on that if I decide on using that.

**Comment by leojonathanoh** [comment]
reopening, will implement in https://github.com/theohbrothers/ConvertOneNote2MarkDown/milestone/1

**Comment by leojonathanoh** [comment]
hey @magi44ken, this configuration feature has been added in [`v2.8.0`](https://github.com/theohbrothers/ConvertOneNote2MarkDown/releases/tag/v2.8.0).
