### ISSUE TITLE
Screenshots not imported properly

### ISSUE THREAD

**Issue by diyaa59** [theohbrothers/ConvertOneNote2MarkDown#183]
## Bug

The screenshots show with a logo with a big x in the middle:

![image](https://github.com/theohbrothers/ConvertOneNote2MarkDown/assets/26883110/4041bf69-8506-4d1b-bacf-04a9e83dfca8)

## Expectation

The screenshots would show up as they are presented in OneNote.

## Discussion

I am not sure if this is a bug or an issue. I have done the conversion 3 times so far with different markdown conversion formats.

I have used the one on the README page of this repository that is recommended for Obsidian:

```powershell
$conversion = 'markdown-simple_tables-multiline_tables-grid_tables+pipe_tables-bracketed_spans+native_spans+startnum'
```

I am wondering if I have missed anything?

## Environment

**Output of Configuration**

```powershell
Configuration:
dryRun: 0
notesdestpath: 'C:\Users\karl\Downloads\ConvertOneNote2MarkDown-master\OneNote'
targetNotebook: My-Notes
usedocx: 1
keepdocx: 1
docxNamingConvention: 1
mdFileNameAndFolderNameMaxLength: 32
prefixFolders: 1
medialocation: 2
**conversion: markdown-simple_tables-multiline_tables-grid_tables+pipe_tables-fenced_code_attributes-inline_code_attributes-fenced_code_attributes**
headerTimestampEnabled: 1
keepspaces: 1
keepescape: 3
newlineCharacter: 2
exportPdf: 1
```

**Output of `$PSVersionTable`**

```powershell
PS > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22621.2506
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.2506
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by leojonathanoh** [comment]
That is strange. Screenshots are no different from normal images, in that they should be converted without their content being mutated. Perhaps you can try adding other images before converting and see if they are fully preserved during conversion. If they are preserved, screenshots would be preserved as well. From my experience with OneNote and Pandoc, there is no reason for this to happen. 

Perhaps you can try disabling any OneNote extensions before conversion since they have been shown to cause problems (though unlikely). See the FAQ in readme.

**Comment by iau4u** [comment]
I have the same issue and could observe, that in my imported notes only .png images struggles, .jpeg-images work like a charm.
By the way, a great tool! When this problem is solved I'll get rid of the proprietary and risky .one format :-)

**Comment by leojonathanoh** [comment]
The script converts onenote pages to `.docx` (using onenote export API), and converts `.docx` to `.md` using pandoc. 

To find out the cause:

1. After converting, open the intermediate `.docx` file and ensure it preserves all images. If the .docx files does not preserve images, then the problem might be a bug in OneNote export-to-docx functionality.
1. Try manually exporting the same OneNote page as `.docx`. If the resulting `.docx` has the same issue as the intermediate `.docx` file, the problem should indeed be with OneNote's export-to-docx functionality. Otherwise, the problem may lie with the export OneNote publish API.

**Comment by diyaa59** [comment]
> I have the same issue and could observe, that in my imported notes only .png images struggles, .jpeg-images work like a charm. By the way, a great tool! When this problem is solved I'll get rid of the proprietary and risky .one format :-)

I just went back and checked most of the files (I got about 4500 notes 🙂) Some of the notes do have screenshots. I think it might be something to do with the way they were pasted/attached into OneNote.

**Comment by leojonathanoh** [comment]
hmm, there are instances where somehow the onenote page may be "bugged", see [this FAQ](https://github.com/theohbrothers/ConvertOneNote2MarkDown#error-exception-calling-publish-with-4-arguments-the-remote-procedure-call-failed-exception-from-hresult-0x800706be), and a few users mentioned copying the pages into another notebook to "fix" it, and then convert. Perhaps you can try that 😄

**Comment by chrisxfire** [comment]
Hi,

I came across this as I was trying to solve for the same issue. Some additional details:
* As @diyaa59 noted, this appears to only happen with PNG, not JPG files.
* Copying the pages into another notebook did not fix the issue for me.

I've resorted to having to convert all of the PNG files to JPG files before converting.

**Comment by goldfish911** [comment]
I had this issue as well but there is an additional troubleshooting step @chrisxfire 

In OneNote's options there is a tickbox for 'Download All Files and Images'. MAKE SURE THIS BOX IS TICKED and sync all notebooks. Since I've done so , the images actually appear to be exported properly instead of as blank placeholders, for both PNG and JPEG. 

This should probably be added as a step alongside downloading a notebook locally to begin with.

**Comment by chrisxfire** [comment]
> I had this issue as well but there is an additional troubleshooting step @chrisxfire 
> 
> 
> 
> In OneNote's options there is a tickbox for 'Download All Files and Images'. MAKE SURE THIS BOX IS TICKED and sync all notebooks. Since I've done so , the images actually appear to be exported properly instead of as blank placeholders, for both PNG and JPEG. 
> 
> 
> 
> This should probably be added as a step alongside downloading a notebook locally to begin with.

Great find. Thanks for sharing @goldfish911 !

**Comment by silasg** [comment]
> I had this issue as well but there is an additional troubleshooting step [@chrisxfire](https://github.com/chrisxfire)
> 
> In OneNote's options there is a tickbox for 'Download All Files and Images'. MAKE SURE THIS BOX IS TICKED and sync all notebooks. Since I've done so , the images actually appear to be exported properly instead of as blank placeholders, for both PNG and JPEG.
> 
> This should probably be added as a step alongside downloading a notebook locally to begin with.

This was needed for me as well. Maybe worth adding this hit to the FAQ
