### ISSUE TITLE
Feature: Filename and Folder Name use space instead of dash

### ISSUE THREAD

**Issue by magi44ken** [theohbrothers/ConvertOneNote2MarkDown#20]
After I import the md files into Joplin, I notice the note title and notebook name have dashes between words. Can you add option to allow the user to choose which format to use? Right now I have to use file rename app to rename the filename and folder name using space.

**Comment by nixsee** [comment]
Hi, I dont have time to look into this. You or someone else is welcome to submit a pull request to add the functionality. In lieu of that, you should be able to do a global find and replace in a text editor like VS Code or Notepad++

**Comment by nixsee** [comment]
@magi44ken Please continue over at https://github.com/theohbrothers/ConvertOneNote2MarkDown-v2

**Comment by leojonathanoh** [comment]
@magi44ken `.md` is a developer-ish format and I would assume that in general most users who use this converter tool would prefer their markdown files names to be unixy (i.e. with dashes / underscores instead of spaces) because of better integration with the command line and tools in general. But I also understand the aesthetics that comes with spaces, which some Windows users may like (after all Onenote and Windows are closely related. I think it would be nice to have an option too.

**Comment by leojonathanoh** [comment]
hey @magi44ken the feature is implemented in `v2.9.0`.

**Comment by leojonathanoh** [comment]
This feature was rolled back in [`v2.11.0`](https://github.com/theohbrothers/ConvertOneNote2MarkDown/releases/tag/v2.11.0), see #54 for more details.
