### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by Wizz4rrd** [theohbrothers/ConvertOneNote2MarkDown#21]
Hi, 

When using the script, whatever type of MD I select my OneNote tables are not well migrated to MD tables.

For example a OneNote table: 
![image](https://user-images.githubusercontent.com/39056039/127405246-08308191-cc7d-4777-b530-312bbd091d4a.png)

The same table (part of) but in Obsidian / Markdown: 

![image](https://user-images.githubusercontent.com/39056039/127405463-7cf7a263-797b-4fa3-83d7-3fac7514723b.png)

**Comment by leojonathanoh** [comment]
@Wizz4rrd i also had this issue and it is related to using the option `$keepspaces = 1` https://github.com/nixsee/ConvertOneNote2MarkDown/blob/master/ConvertOneNote2MarkDown-v2.ps1#L216, where it strips out `<` and `>` brackets, which breaks inline `html` code.

I believe this is a bug, because im not exactly sure how stripping those `<` and `>` brackets relates to clearing double spaces. So perhaps you can remove that portion in the script.

**Comment by nixsee** [comment]
I honestly dont remember what the <  > could have been about, and dont have time to look into this, now or into the foreseeable future. 

@leojonathanoh You seem keen and far more talented than me. I just asked in another issue you posted in if you would be interested in taking over the development of this script in some way. Let me know what you think and how we could proceed with it.

**Comment by nixsee** [comment]
@Wizz4rrd Please continue over at https://github.com/theohbrothers/ConvertOneNote2MarkDown-v2

**Comment by leojonathanoh** [comment]
hey @Wizz4rrd, this has been fixed in [`v2.8.0`](https://github.com/theohbrothers/ConvertOneNote2MarkDown/releases/tag/v2.8.0), please let me know if you still get html markup issues.

**Comment by Wizz4rrd** [comment]
Hi @leojonathanoh 

I don't have any issues now, works great, thanks!

**Comment by leojonathanoh** [comment]
@Wizz4rrd glad it works for you 😃
