### ISSUE TITLE
 Unable to find type [Microsoft.Office.InterOp.OneNote.HierarchyScope].

### ISSUE THREAD

**Issue by kamilNope** [theohbrothers/ConvertOneNote2MarkDown#5]
Run new office onenote with admin permissions and powershell with admin permissions 
Version	Windows 10 Pro
Version 20H2
Compilation	19042.631

Error    Unable to find type [Microsoft.Office.InterOp.OneNote.HierarchyScope].
At C:\GIT\ConvertOneNote2MarkDown-master\ConvertOneNote2MarkDown-v2.ps1:357 char:31
 ... erarchy("", [Microsoft.Office.InterOp.OneNote.HierarchyScope]::hsPage ...
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : InvalidOperation: (Microsoft.Offic....HierarchyScope:TypeName) [], RuntimeException
     FullyQualifiedErrorId : TypeNotFound

**Comment by aparente** [comment]
Getting this same error on a Windows 10 Pro VM running on Azure. Running in Powershell administrative mode. 
```
New-Object : Retrieving the COM class factory for component with CLSID {00000000-0000-0000-0000-000000000000} failed
due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
At C:\Users\aparente\Documents\ConvertOneNote2MarkDown4Obsidian-master\ConvertOneNote2MarkDown4Obsidian-master\ConvertO
neNote2MarkDown-v2.ps1:721 char:16
+     $OneNote = New-Object -ComObject OneNote.Application
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [New-Object], COMException
    + FullyQualifiedErrorId : NoCOMClassIdentified,Microsoft.PowerShell.Commands.NewObjectCommand

Unable to find type [Microsoft.Office.InterOp.OneNote.HierarchyScope].
At C:\Users\aparente\Documents\ConvertOneNote2MarkDown4Obsidian-master\ConvertOneNote2MarkDown4Obsidian-master\ConvertO
neNote2MarkDown-v2.ps1:724 char:31
+ ... erarchy("", [Microsoft.Office.InterOp.OneNote.HierarchyScope]::hsPage ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Offic....HierarchyScope:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

Total links found       :       0
        Matched         :       0
        Ambiguous       :       0
        Not matched     :       0
Exception calling "ReleaseComObject" with "1" argument(s): "Object reference not set to an instance of an object."
At C:\Users\aparente\Documents\ConvertOneNote2MarkDown4Obsidian-master\ConvertOneNote2MarkDown4Obsidian-master\ConvertO
neNote2MarkDown-v2.ps1:928 char:5
+     [System.Runtime.Interopservices.Marshal]::ReleaseComObject($OneNo ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NullReferenceException

Remove-Variable : Cannot find a variable with the name 'OneNote'.
At C:\Users\aparente\Documents\ConvertOneNote2MarkDown4Obsidian-master\ConvertOneNote2MarkDown4Obsidian-master\ConvertO
neNote2MarkDown-v2.ps1:929 char:5
+     Remove-Variable OneNote
+     ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (OneNote:String) [Remove-Variable], ItemNotFoundException
    + FullyQualifiedErrorId : VariableNotFound,Microsoft.PowerShell.Commands.RemoveVariableCommand

```

**Comment by winstonleedev** [comment]
Make sure that you are running the **Office version**, not the Windows Store version of One Note.

What's the difference? The Office version has a slightly taller ribbon (3 lines) instead of 1 line in the Windows Store version

Office version
![onenoteoffice](https://user-images.githubusercontent.com/9567726/104681650-2aa15a00-5736-11eb-9567-867594668808.jpg)

Store version
<img width="907" alt="Screen Shot 2021-01-15 at 01 33 20 PM" src="https://user-images.githubusercontent.com/9567726/104681686-41e04780-5736-11eb-97bd-5ce10be63901.png">

**Comment by nixsee** [comment]
Sorry for being late to this - did @thanhphu 's suggestion work? Yes, it is necessary (and advisable, due to better features) to use the Office version, which is free here https://www.onenote.com/Download

**Comment by rustam-python** [comment]
The same problem. I tried with The Office version.

```
InvalidOperation: K:\tmp\OneNote\ConvertOneNote2MarkDown-2.5\ConvertOneNote2MarkDown-v2.ps1:357:31
Line |
 357 |  … erarchy("", [Microsoft.Office.InterOp.OneNote.HierarchyScope]::hsPage …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Unable to find type [Microsoft.Office.InterOp.OneNote.HierarchyScope].

0
```

Upd. My bad - it works if PowerShell and OneNote (The Office version, not usual one!) are both started as Administrator.

**Comment by nixsee** [comment]
@rustam-python just curious, what caused your initial problem? Did you use Office version or Windows Store version? Admin or normal?

**Comment by rustam-python** [comment]
> @rustam-python just curious, what caused your initial problem? Did you use Office version or Windows Store version? Admin or normal?

Script is not working with OneNote started as Administrator and PowerShell started as non-Administrator. In all tries I used The Office Version of OneNote.

**Comment by nixsee** [comment]
Thanks. So it was just the admin status not matching. Yeah, that's covered in the instructions, so I won't look into this any further and close the issue.

**Comment by slappycat2** [comment]
Hi Nixsee, Not sure why you closed this. He said he is still running into the same problem and I am too. I'm running 2016, Desktop version, both, VS Code and OneNote, running as admin, and I get the exact same error. Any ideas?

**Comment by nixsee** [comment]
@slappycat2 I closed it because it is a user error issue - they didn't read the instructions. 

Try running Powershell directly, rather than in VS Code - perhaps the Powershell in VS Code is not running as Admin. Alternatively, run both without admin (I don't use admin for either when I run it). 

Moreover, these errors are outside of the scope of the script - they are a windows/powershell/office problem which each person will have to resolve for themselves.

**Comment by slappycat2** [comment]
Tried all of the above and no luck. I'll keep playing with it.

UPDATE - For others running into this issue, I got it working, finally. The key for me turned out to be that I had to run it in the Powershell ISE (not just the Powershell). So, to recap:
1. Run OneNote as Admin
2. Use PS ISE as ADMIN.
3. Set-ExecutionPolicy Bypass -Scope Process      (Answer Yes-To-All, when prompted)
4. Run the program at the commandline.
HTH!

**Comment by nixsee** [comment]
Good to hear you got it working. Does normal Powershell work if you run "Set-ExecutionPolicy Bypass -Scope Process" in it?

**Comment by slappycat2** [comment]
@Nixsee: No, it didn't. I had to use ADMIN, too. If I find anything else worth sharing, I'll post here! Thanks!

**Comment by rustam-python** [comment]
> Good to hear you got it working. Does normal Powershell work if you run "Set-ExecutionPolicy Bypass -Scope Process" in it?

My bad - I forgot to mention that last time. Yes, firstly I tried without `Set-ExecutionPolicy Bypass -Scope Process` - it is not worked. After I enabled it - it was ok.

**Comment by nixsee** [comment]
Good to hear. So, just to be thorough, does normal PowerShell (not ISE) work in non-admin mode (OneNote in non-admin as well) if you run it with `Set-ExecutionPolicy Bypass -Scope Process`? Or does it only work with admin and set-executionpolicy?

**Comment by rustam-python** [comment]
> Good to hear. So, just to be thorough, does normal PowerShell (not ISE) work in non-admin mode (OneNote in non-admin as well) if you run it with `Set-ExecutionPolicy Bypass -Scope Process`? Or does it only work with admin and set-executionpolicy?

No, only in admin mode with `Set-ExecutionPolicy Bypass -Scope Process`.

**Comment by nixsee** [comment]
Ok, so pretty much as I have described in the Readme... 

![image](https://user-images.githubusercontent.com/24255237/120078219-9b08a200-c06b-11eb-82ec-f05e2e2c8453.png)

Hopefully no one else will need to raise an issue about this again, now that it is all documented clearly here

**Comment by leojonathanoh** [comment]
Just wanted to leave a note to future readers that this happens because the script requires Powershell 5 (Powershell ISE will work too). The error shows up on `pwsh` (aka powershell core, aka Powershell >=6).

In contrast to the suggestion above https://github.com/theohbrothers/ConvertOneNote2MarkDown/issues/5#issuecomment-850732968, the script does not require admin privileges. `Set-ExecutionPolicy Bypass -Scope Process ` is required, as described in the readme.

**Comment by leojonathanoh** [comment]
Support for powershell core added in #43.

If this happens on Windows Powershell <=5.x then perhaps its due to missing Onenote assemblies because the user might not have installed the desktop version of Onenote 2016. Warning message about this added in #44.

Both will be included in `v2.10.0`.

If this still happens, please post your environment so we can find out the cause.

**Comment by mvelbaum** [comment]
FWIW, I also encountered the same issue while running the script in PowerShell Core 7 with Office 2021 and the solution was to run the script from PowerShell 5 with `Set-ExecutionPolicy Bypass -Scope Process` -- no admin privileges required.

**Comment by DarkStar777** [comment]
For what it's worth, even following all the guidelines I'm still getting this error EXCEPT it works in PowerShell ISE (which it says doesn't support long paths and not to use).

I tried running both OneNote and PowerShell Core 7 as myself, and running both with Admin privileges; I also tried both with and without the ExecutionPolicy change (worked with it):

`Set-ExecutionPolicy -ExecutionPolic Bypass -Scope Process`

PowerShell Core 7.4.0 preview.5 (technically newer than listed as 7.0.x)
Windows 11 version 22H2 OS Build 22621.2134
Office 365 suite, Word Version 2307 Build 16.0.166262.20170) 64-Bit
OneNote 365 MSO (Version 2307 Build 16626.20170) 64-Bit (Desktop version)

**Comment by leojonathanoh** [comment]
@DarkStar777 

`Set-ExecutionPolicy -ExecutionPolic Bypass -Scope Process` should almost always be needed.

Please use Powershell core 7.0.x. Powershell 7.1 and above is not supported. See readme for the reason.

> For what it's worth, even following all the guidelines I'm still getting this error EXCEPT it works in PowerShell ISE (which it says doesn't support long paths and not to use).

Windows Powershell ISE may work, but when paths get long (e.g. lots of layers of section groups), there will be errors. It is recommended to just use Windows Powershell because it will just work.
